# Chapter 6. Data Loading, Storage, and File Formats

In this first cell we are going to import the libraries we need for this notebook, and we are going to set display parameters for <b>pandas</b> and <b>matplotlib</b>

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
pd.options.display.max_colwidth = 75
pd.options.display.max_columns = 20
np.set_printoptions(precision=4, suppress=True)

Reading data and making it accessible is a necessary first step for using most of the tools in this class. 

The term <b>parsing</b> is also sometimes used to describe loading text data and interpreting it as tables and different data types. 

We're going to focus on data input and output using <b>pandas</b>, though there are numerous tools in other libraries to help with reading and writing data in various formats.

Input and output typically fall into a few main categories: 
- reading text files and other more efficient on-disk file formats
- loading data from databases
- interacting with network sources like web APIs.

### DataFrames

A <b>DataFrame</b> is a two-dimensional, tabular data structure in Python, provided by the <b>pandas</b> library. 

It is one of the most widely used data structures for data analysis and manipulation. 

A DataFrame is similar to a table in a database or an Excel spreadsheet, with rows and columns.

We can create a DataFrame by loading tabular style data into the pandas DataFrame object.

In [2]:
import pandas as pd 

# Create a DataFrame from a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

<b>DataFrames</b> will be covered in more detail in lecture 9 (Chapter 5 in the book)

We are introducing this tool early so that we can discuss more complicated IO functions

## 6.1 Reading and Writing Data in Text Format

<b>pandas</b> features a number of functions for reading tabular data as a <b>DataFrame</b> object. 

Table 6-1 summarizes some of them; <b>pandas.read_csv</b> is one of the most frequently used in the book. 

We will look at binary data formats later in Section <b>6.2, “Binary Data Formats”</b>.

Table 6-1. Text and binary data loading functions in pandas

|Function|	Description|
|---|---|
|read_csv|	Load delimited data from a file, URL, or file-like object; use comma as default delimiter|
|read_fwf|	Read data in fixed-width column format (i.e., no delimiters)|
|read_clipboard|	Variation of read_csv that reads data from the clipboard; useful for converting tables from web pages|
|read_excel|	Read tabular data from an Excel XLS or XLSX file|
|read_hdf|	Read HDF5 files written by pandas|
|read_html|	Read all tables found in the given HTML document|
|read_json|	Read data from a JSON (JavaScript Object Notation) string representation, file, URL, or file-like object|
|read_feather|	Read the Feather binary file format|
|read_orc|	Read the Apache ORC binary file format|
|read_parquet|	Read the Apache Parquet binary file format|
|read_pickle|	Read an object stored by pandas using the Python pickle format|
|read_sas|	Read a SAS dataset stored in one of the SAS system’s custom storage formats|
|read_spss|	Read a data file created by SPSS|
|read_sql|	Read the results of a SQL query (using SQLAlchemy)|
|read_sql_table|	Read a whole SQL table (using SQLAlchemy); equivalent to using a query that selects everything in that table using read_sql|
|read_stata|	Read a dataset from Stata file format|
|read_xml|	Read a table of data from an XML file|

We’ll give an overview of the mechanics of these functions, which are meant to convert text data into a <b>DataFrame</b>. 

The optional arguments for these functions may fall into a few categories:

<b>Indexing</b>
- Can treat one or more columns as the returned DataFrame, and whether to get column names from the file, arguments you provide, or not at all.
  
<b>Type inference and data conversion</b>
  - Includes the user-defined value conversions and custom list of missing value markers.
    
<b>Date and time parsing</b>
  - Includes a combining capability, including combining date and time information spread over multiple columns into a single column in the result.
    
<b>Iterating</b>
  - Support for iterating over chunks of very large files.
    
<b>Unclean data issues</b>
  - Includes skipping rows or a footer, comments, or other minor things like numeric data with thousands separated by commas.

Because of how messy data in the real world can be, some of the data loading functions (especially <b>pandas.read_csv</b>) have accumulated a long list of optional arguments over time. 

The online pandas documentation has many examples about how each of these works, so if you’re struggling to read a particular file, there might be a similar enough example to help you find the right parameters.

https://pandas.pydata.org/docs/

Some of these functions perform <b>type inference</b>, because the column <b>data types</b> are not part of the data format. 

That means you don’t necessarily have to specify which columns are numeric, integer, Boolean, or string. 

Other data formats, like HDF5, ORC, and Parquet, have the data type information embedded in the format.

Handling dates and other custom types can require extra effort.


Let’s start with a small comma-separated values (CSV) text file:

In [5]:
!cat ../examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

<blockquote>
    
#### Note

Here we used the Unix <b>cat</b> shell command to print the raw contents of the file to the screen. 

If you’re on Windows, you can use <b>type</b> instead of <b>cat</b> to achieve the same effect within a Windows terminal (or command line).
</blockquote>

Since this is comma-delimited, we can then use <b>pandas.read_csv</b> to read it into a <b>DataFrame</b>:

In [7]:
df = pd.read_csv("../examples/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
!cat ../examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

To read this file, you have a couple of options. 

You can allow <b>pandas</b> to assign default column names, or you can specify names yourself:

In [11]:
pd.read_csv("../examples/ex2.csv", header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [13]:
pd.read_csv("../examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Suppose you wanted the <b>message</b> column to be the <b>index</b> of the returned DataFrame. 

You can either indicate you want the column at index 4, or named "message" using the <b>index_col</b> argument:

In [15]:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("../examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

If you want to form a <b>hierarchical</b> index (discussed in <b>Section 8.1, “Hierarchical Indexing”</b>) from multiple columns, pass a list of column numbers or names:

In [18]:
!cat ../examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [20]:
parsed = pd.read_csv("../examples/csv_mindex.csv",
                     index_col=["key1", "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In some cases, a table might not have a fixed <b>delimiter</b>, instead using whitespace or some other pattern to separate fields. 

Consider a text file that looks like this:

In [23]:
!cat ../examples/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

While you could do some munging by hand, the fields here are separated by a variable amount of <b>whitespace</b>. 

In these cases, you can pass a <b>regular expression</b> as a delimiter for <b>pandas.read_csv</b>. 

This can be expressed by the regular expression <b>\s+</b>, (denotes 1 or more <b>spaces</b> or <b>tabs</b>) so we have then:

In [25]:
result = pd.read_csv("../examples/ex3.txt", sep="\s+")
result

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/var/folders/r3/gmt08cnn7lzdwnng743vjxmw0000gp/T/ipykernel_54747/3148586409.py:1: SyntaxWarning: invalid escape sequence '\s'
  result = pd.read_csv("../examples/ex3.txt", sep="\s+")

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Because there was one fewer column name than the number of data rows, <b>pandas.read_csv</b> infers that the first column should be the DataFrame’s index in this special case.

The file parsing functions have many additional arguments to help you handle the wide variety of exception file formats that occur (see a partial listing in Table 6.2).

## Table 6.2 Some pandas.read_csv function arguments

|Argument|	Description|
|---|---|
|path|	String indicating filesystem location, URL, or file-like object.|
|sep or delimiter|	Character sequence or regular expression to use to split fields in each row.|
|header|	Row number to use as column names; defaults to 0 (first row), but should be None if there is no header row.|
|index_col|	Column numbers or names to use as the row index in the result; can be a single name/number or a list of them for a hierarchical index.|
|names|	List of column names for result.|
|skiprows|	Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip.|
|na_values|	Sequence of values to replace with NA. They are added to the default list unless keep_default_na=False is passed.|
|keep_default_na|	Whether to use the default NA value list or not (True by default).|
|comment|	Character(s) to split comments off the end of lines.|
|parse_dates|	Attempt to parse data to datetime; False by default. If True, will attempt to parse all columns. Otherwise, can specify a list of column numbers or names to parse. If element of list is tuple or list, will combine multiple columns together and parse to date (e.g., if date/time split across two columns).|
|keep_date_col|	If joining columns to parse date, keep the joined columns; False by default.|
|converters|	Dictionary containing column number or name mapping to functions (e.g., {"foo": f} would apply the function f to all values in the "foo" column).|
|dayfirst|	When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -> June 7, 2012); False by default.|
|date_parser|	Function to use to parse dates.|
|nrows|	Number of rows to read from beginning of file (not counting the header).|
|iterator|	Return a TextFileReader object for reading the file piecemeal. This object can also be used with the with statement.|
|chunksize|	For iteration, size of file chunks.|
|skip_footer|	Number of lines to ignore at end of file.|
|verbose|	Print various parsing information, like the time spent in each stage of the file conversion and memory use information.|
|encoding|	Text encoding (e.g., "utf-8 for UTF-8 encoded text). Defaults to "utf-8" if None.|
|squeeze|	If the parsed data contains only one column, return a Series.|
|thousands|	Separator for thousands (e.g., "," or "."); default is None.|
|decimal|	Decimal separator in numbers (e.g., "." or ","); default is ".".|
|engine|	CSV parsing and conversion engine to use; can be one of "c", "python", or "pyarrow". The default is "c", though the newer "pyarrow" engine can parse some files much faster. The "python" engine is slower but supports some features that the other engines do not.|

For example, you can skip the first, third, and fourth rows of a file with <b>skiprows</b>:

In [28]:
!cat ../examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [30]:
pd.read_csv("../examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

## Handling Missing Data

Handling missing values is an important and frequently nuanced part of the file reading process. 

Missing data is usually either not present (empty string) or marked by some sentinel (placeholder) value. 

By default, pandas uses a set of commonly occurring sentinels, such as <b>NA</b> and <b>NULL</b>:

### List of Strings Identified as Missing Data by Pandas Dataframe


|Missing Value Indicator|	Description|
|---|---|
|"NA"	|Common representation of missing data.|
|"N/A"	|Another common representation of missing data.|
|"NULL"	|Often used in databases for missing values.|
|"NaN"	|Floating-point representation for missing data.|
|"n/a"	|Lowercase version of "N/A".|
|"#N/A"	|Spreadsheet-style missing value indicator.|
|"#NA"	|Similar to "#N/A".|
|"N/A N/A"|	Rarely used but recognized by Pandas.|
|"NA#NUM!"|	Rarely used but recognized by Pandas.|
|"-1.#IND"|	IEEE 754 representation for invalid numbers.|
|"1.#QNAN"|	IEEE 754 representation for quiet NaN.|
|"nan"	|Lowercase version of "NaN".|
|"null"	|Common in JSON and databases.|
| ""| Empty string|

In [33]:
!cat ../examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [35]:
result = pd.read_csv("../examples/ex5.csv")
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Recall that pandas outputs missing values as <b>NaN</b>, so we have two null or missing values in result:

In [37]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

The <b>na_values</b> option accepts a sequence of strings to add to the default list of strings recognized as missing:

In [39]:
result = pd.read_csv("../examples/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

<b>pandas.read_csv</b> has a list of many default <b>NA</b> value representations, but these defaults can be disabled with the <b>keep_default_na</b> option:

In [41]:
result2 = pd.read_csv("../examples/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [43]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

When disabling <b>default_na</b>, we have to define our NA values

In [46]:
result3 = pd.read_csv("../examples/ex5.csv", keep_default_na=False,
                      na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [48]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

Different NA sentinels can be specified for each column in a dictionary:

In [50]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("../examples/ex5.csv", na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

## Reading Text Files in Pieces

When processing very large files or figuring out the right set of arguments to correctly process a large file, you may want to read only a small piece of a file or iterate through smaller chunks of the file.

Before we look at a large file, we make the <b>pandas</b> display settings more compact:

In [53]:
pd.options.display.max_rows = 10

Now we have:

In [55]:
result = pd.read_csv("../examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

The elipsis marks <b>...</b> indicate that rows in the middle of the <b>DataFrame</b> have been omitted.

If you want to read only a small number of rows from the top of the file (avoiding reading the entire file), specify that with <b>nrows</b>:

In [57]:
pd.read_csv("../examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

To read a file in pieces, specify a <b>chunksize</b> as a number of rows:

In [59]:
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)
type(chunker)

pandas.io.parsers.readers.TextFileReader

The <b>TextFileReader</b> object returned by <b>pandas.read_csv</b> allows you to <b>iterate</b> over the parts of the file according to the <b>chunksize</b>.

For example, we can iterate over <b>ex6.csv</b>, aggregating the <b>value_counts</b> in the <b>"key"</b> column, like so:

In [62]:
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)
#chunker = pd.read_csv("../examples/ex6.csv")

tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

We have then:

In [65]:
tot[:]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
     ...
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

<b>TextFileReader</b> is also equipped with a <b>get_chunk</b> method that enables you to read pieces of an arbitrary size.

## Writing Data to Text Format

Data can also be exported to a delimited format. 

Let’s consider one of the CSV files read before:

In [69]:
data = pd.read_csv("../examples/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [74]:
!cat ../examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

Using <b>DataFrame’s</b> <b>to_csv</b> method, we can write the data out to a comma-separated file:

In [72]:
! rm ../examples/out.csv #remove old output file
data.to_csv("../examples/out.csv")
!cat ../examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

Other delimiters can be used, of course (writing to <b>sys.stdout</b> so it prints the text result to the console rather than a file):

In [78]:
import sys

data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

Missing values appear as empty strings in the output. 

You might want to denote them by some other sentinel value:

In [80]:
data.to_csv(sys.stdout, sep=",", na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

With no other options specified, both the <b>row</b> and <b>column</b> <b>labels</b> are written. 

Both of these can be disabled:

In [83]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

You can also write only a subset of the columns, and in an order of your choosing:

In [85]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

## Working with Other Delimited Formats

It’s possible to load most forms of tabular data from disk using functions like <b>pandas.read_csv</b>. 

In some cases, however, some manual processing may be necessary. 

It’s not uncommon to receive a file with one or more malformed lines that trip up <b>pandas.read_csv</b>. 

To illustrate the basic tools, consider a small CSV file:

In [89]:
!cat ../examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

For any file with a single-character delimiter, you can use Python’s built-in <b>csv</b> module.

To use it, pass any open file or file-like object to <b>csv.reader</b>:

In [91]:
import csv
f = open("../examples/ex7.csv")
reader = csv.reader(f)

Iterating through the reader like a file yields lists of values with any quote characters removed:

In [94]:
for line in reader:
    print(line)
f.close()

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

From there, it’s up to you to do the wrangling necessary to put the data in the form that you need. 

Let’s take this step by step. First, we read the file into a list of lines:

In [96]:
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [98]:
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

Then we split the lines into the header line and the data lines:

In [100]:
header, values = lines[0], lines[1:]

In [102]:
zip(header, zip(*values))

Then we can create a dictionary of data columns using a <b>dictionary comprehension</b> and the expression <b>zip(*values)</b> (beware that this will use a lot of memory on large files), which transposes rows to columns:

In [104]:
data_dict = { h: v for h, v in zip(header, zip(*values)) }
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

CSV files come in many different flavors. 

To define a new format with a different delimiter, string quoting convention, or line terminator, we could define a simple subclass of <b>csv.Dialect</b>:

In [ ]:
class my_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

In [ ]:
f = open("../examples/ex7.csv")
reader = csv.reader(f, dialect=my_dialect)

We could also give individual CSV dialect parameters as keywords to <b>csv.reader</b> without having to define a subclass:

In [ ]:
reader = csv.reader(f, delimiter="|")

The possible options (attributes of <b>csv.Dialect</b>) and what they do can be found in Table 6.3

Table 6.3 CSV dialect options

|Argument|	Description|
|---|---|
|delimiter|	One-character string to separate fields; defaults to ",".|
|lineterminator|	Line terminator for writing; defaults to "\r\n". Reader ignores this and recognizes cross-platform line terminators.|
|quotechar|	Quote character for fields with special characters (like a delimiter); default is '"'.|
|quoting|	Quoting convention. Options include csv.QUOTE_ALL (quote all fields), csv.QUOTE_MINIMAL (only fields with special characters like the delimiter), csv.QUOTE_NONNUMERIC, and csv.QUOTE_NONE (no quoting). See Python’s documentation for full details. Defaults to QUOTE_MINIMAL.|
|skipinitialspace|	Ignore whitespace after each delimiter; default is False.|
|doublequote|	How to handle quoting character inside a field; if True, it is doubled (see online documentation for full detail and behavior).|
|escapechar|	String to escape the delimiter if quoting is set to csv.QUOTE_NONE; disabled by default.|

<blockquote>
    
### Note

For files with more complicated or fixed multicharacter delimiters, you will not be able to use the <b>csv</b> module. In those cases, you’ll have to do the line splitting and other cleanup using the string’s split method or the regular expression method <b>re.split</b>. Thankfully, <b>pandas.read_csv</b> is capable of doing almost anything you need if you pass the necessary options, so you only rarely will have to parse files by hand.

</blockquote>

To write delimited files manually, you can use <b>csv.writer</b>. 

It accepts an open, writable file object and the same dialect and format options as <b>csv.reader</b>:

In [ ]:
with open("mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

## JSON Data

JSON (short for JavaScript Object Notation) has become one of the standard formats for sending data by HTTP request between web browsers and other applications. 

It is a much more free-form data format than a tabular text form like CSV. 

Here is an example:

In [ ]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

JSON is very nearly valid Python code with the exception of its null value null and some other nuances (such as disallowing trailing commas at the end of lists). 

The basic types are objects (dictionaries), arrays (lists), strings, numbers, Booleans, and nulls. 

All of the keys in an object must be strings. There are several Python libraries for reading and writing JSON data. 

I’ll use json here, as it is built into the Python standard library. 

To convert a JSON string to Python form, use json.loads:

In [ ]:
import json
result = json.loads(obj)
result

<b>json.dumps</b>, on the other hand, converts a Python object back to JSON:

In [ ]:
asjson = json.dumps(result)
asjson

How you convert a JSON object or list of objects to a DataFrame or some other data structure for analysis will be up to you. 

Conveniently, you can pass a list of dictionaries (which were previously JSON objects) to the DataFrame constructor and select a subset of the data fields:

In [ ]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

The <b>pandas.read_json</b> can automatically convert JSON datasets in specific arrangements into a <b>Series</b> or <b>DataFrame</b>. 

For example:

In [ ]:
!cat ../examples/example.json

The default options for pandas.read_json assume that each object in the JSON array is a row in the table:

In [ ]:
data = pd.read_json("../examples/example.json")
data

For an extended example of reading and manipulating JSON data (including nested records), see the USDA food database example in <b>Chapter 13</b>.

If you need to export data from pandas to JSON, one way is to use the <b>to_json</b> methods on <b>Series</b> and <b>DataFrame</b>:

In [ ]:
data.to_json(sys.stdout)

In [ ]:
data.to_json(sys.stdout, orient="records")

## XML and HTML: Web Scraping

Python has many libraries for reading and writing data in the ubiquitous <b>HTML</b> and <b>XML</b> formats. 

Examples include <b>lxml, beautifulsoup, and html5lib</b>.

While lxml is comparatively much faster in general, the other libraries can better handle malformed HTML or XML files.

<b>pandas</b> has a built-in function, <b>pandas.read_html</b>, which uses all of these libraries to automatically parse tables out of HTML files as DataFrame objects. 

To show how this works, we downloaded an HTML file from the US FDIC showing bank failures.

First, we need to install some additional libraries used by <b>read_html</b>:

In [ ]:
conda install lxml beautifulsoup4 html5lib

If you are not using <b>conda</b>, <b>pip install lxml</b> should also work.

The <b>pandas.read_html</b> function by default searches for and attempts to parse all tabular data contained within <b>\<table\></b> tags. 

The result is a <b>list</b> of <b>DataFrame</b> objects:

In [ ]:
tables = pd.read_html("../examples/fdic_failed_bank_list.html")
len(tables)

In [ ]:
failures = tables[0]
failures.head()

Because failures has many columns, pandas inserts a line break character <b>\\</b>.

From here we could proceed to do some data cleaning and analysis, like computing the number of bank failures by year:

In [ ]:
close_timestamps = pd.to_datetime(failures["Closing Date"])

In [ ]:
close_timestamps.dt.year.value_counts()

## Parsing XML with lxml.objectify

XML is another common structured data format supporting hierarchical, nested data with metadata. The book you are currently reading was actually created from a series of large XML documents.

Earlier, I showed the <b>pandas.read_html</b> function, which uses either <b>lxml</b> or <b>Beautiful Soup</b> under the hood to parse data from HTML. 

XML and HTML are structurally similar, but XML is more general. Here, I will show an example of how to use lxml to parse data from a more general XML format.

For many years, the New York Metropolitan Transportation Authority (MTA) published a number of data series about its bus and train services in XML format. Here we’ll look at the performance data, which is contained in a set of XML files. 

Each train or bus service has a different file (like <b>Performance_MNR.xml</b> for the Metro-North Railroad) containing monthly data as a series of XML records that look like this:

Using <b>lxml.objectify</b>, we parse the file and get a reference to the root node of the XML file with <b>getroot</b>:

In [ ]:
from lxml import objectify

path = "../datasets/mta_perf/Performance_MNR.xml"
with open(path) as f:
    parsed = objectify.parse(f)
root = parsed.getroot()

<b>root.INDICATOR</b> returns a generator yielding each \<INDICATOR\> XML element. 

For each record, we can populate a dictionary of tag names (like YTD_ACTUAL) to data values (excluding a few tags) by running the following code:

In [ ]:
data = []

skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

Lastly, convert this list of dictionaries into a DataFrame:

In [ ]:
perf = pd.DataFrame(data)
perf.head()

pandas’s <b>pandas.read_xml</b> function turns this process into a one-line expression:

In [ ]:
perf2 = pd.read_xml(path)
perf2.head()

For more complex XML documents, refer to the docstring for <b>pandas.read_xml</b> which describes how to do selections and filters to extract a particular table of interest.

# 6.2 Binary Data Formats

## Pickle Files

One simple way to store (or <b>serialize</b>) data in binary format is using Python’s built-in <b>pickle</b> module. 

<b>pandas</b> objects all have a <b>to_pickle</b> method that writes the data to disk in pickle format:

A <b>pickle</b> file is a binary file that allows you to save and restore complex Python objects without requiring a custom parser. 

It is useful for <b>saving data, sharing Python objects</b>, or <b>caching restartable checkpoints</b>, but it should be used cautiously due to security risks and Python-specific limitations.

<blockquote>

### Warning

A <b>pickle</b> file can be engineered to execute arbitrary code during unpacking (or <b>deserialization</b>), so only trusted sources should be used.
</blockquote>

In [ ]:
frame = pd.read_csv("../examples/ex1.csv")
frame

In [ ]:
frame.to_pickle("../examples/frame_pickle")

Pickle files are in general readable only in Python. 

You can read any “pickled” object stored in a file by using the built-in <b>pickle</b> directly, or even more conveniently using <b>pandas.read_pickle<b>:

In [ ]:
pd.read_pickle("../examples/frame_pickle")

<blockquote>

### Caution

<b>pickle</b> is recommended only as a short-term storage format. 

The danger is that it is hard to guarantee that the format will be stable over time; an object pickled today may not unpickle with a later version of a library. 

<b>pandas</b> has tried to maintain backward compatibility when possible, but at some point in the future it may be necessary to “break” the pickle format.
</blockquote>

<b>pandas</b> has built-in support for several other open source binary data formats, such as <b>HDF5</b>, <b>ORC</b>, and <b>Apache Parquet<b>. 

For example, if you install the <b>pyarrow</b> package, then you can read Parquet files with <b>pandas.read_parquet</b>:

In [ ]:
!rm ../examples/frame_pickle

In [ ]:
fec = pd.read_parquet('../datasets/fec/fec.parquet')

We encourage you to explore different file formats to see how fast they are and how well they work for your analysis.

## Reading Microsoft Excel Files

<b>pandas</b> also supports reading tabular data stored in Excel 2003 (and higher) files using either the <b>pandas.ExcelFile</b> class or <b>pandas.read_excel</b> function. 

Internally, these tools use the add-on packages <b>xlrd</b> and <b>openpyxl</b> to read old-style XLS and newer XLSX files, respectively. 

These must be installed separately from pandas using pip or conda:

In [ ]:
conda install openpyxl xlrd

To use <b>pandas.ExcelFile</b>, create an instance by passing a path to an <b>xls</b> or <b>xlsx</b> file:

In [ ]:
xlsx = pd.ExcelFile("../examples/ex1.xlsx")

This object can show you the list of available sheet names in the file:

In [ ]:
xlsx.sheet_names

Data stored in a sheet can then be read into DataFrame with <b>parse</b>:

In [ ]:
xlsx.parse(sheet_name="Sheet1")

This Excel table has an index column, so we can indicate that with the <b>index_col</b> argument:

In [ ]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

If you are reading multiple sheets in a file, then it is faster to create the <b>pandas.ExcelFile</b>, but you can also simply pass the filename to <b>pandas.read_excel</b>:

In [ ]:
frame = pd.read_excel("../examples/ex1.xlsx", sheet_name="Sheet1")
frame

To write pandas data to Excel format, you must first create an <b>ExcelWriter</b>, then write data to it using the pandas object’s <b>to_excel</b> method:

In [ ]:
writer = pd.ExcelWriter("../examples/ex2.xlsx")
frame.to_excel(writer, "Sheet1")
writer.close()

You can also pass a file path to to_excel and avoid the ExcelWriter:

In [ ]:
frame.to_excel("../examples/ex2.xlsx")

In [ ]:
!rm ../examples/ex2.xlsx

In [ ]:
!rm -f ../examples/mydata.h5

## Using HDF5 Format

<b>HDF5</b> is a respected file format intended for storing large quantities of scientific array data. 

It is available as a C library, and it has interfaces available in many other languages, including Java, Julia, MATLAB, and Python. The “HDF” in HDF5 stands for <b>hierarchical data format</b>. 

Each HDF5 file can store multiple datasets and supporting metadata. Compared with simpler formats, HDF5 supports on-the-fly compression with a variety of compression modes, enabling data with repeated patterns to be stored more efficiently. 

HDF5 can be a good choice for working with datasets that don’t fit into memory, as you can efficiently read and write small sections of much larger arrays.

To get started with HDF5 and pandas, you must first install <b>PyTables</b> by installing the <b>tables</b> package with conda:

In [ ]:
conda install pytables

<blockquote>
Note

Note that the PyTables package is called <b>“tables”</b> in PyPI, so if you install with pip you will have to run <b>pip install tables</b>.
</blockquote>

While it’s possible to directly access HDF5 files using either the <b>PyTables</b> or <b>h5py</b> libraries, pandas provides a high-level interface that simplifies storing Series and DataFrame objects. 

The <b>HDFStore</b> class works like a dictionary and handles the low-level details:

In [ ]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})
store = pd.HDFStore("../examples/mydata.h5")
store["obj1"] = frame
store["obj1_col"] = frame["a"]
store

Objects contained in the HDF5 file can then be retrieved with the same dictionary-like API:

In [ ]:
store["obj1"]

<b>HDFStore</b> supports two storage schemas, <b>"fixed"</b> and <b>"table"</b> (the default is "fixed"). 

The latter is generally slower, but it supports query operations using a special syntax:

In [ ]:
store.put("obj2", frame, format="table")
store.select("obj2", where=["index >= 10 and index <= 15"])
store.close()

The <b>put</b> is an explicit version of the <b>store\["obj2"\] = frame</b> method but allows us to set other options like the storage format.

The <b>pandas.read_hdf</b> function gives you a shortcut to these tools:

In [ ]:
frame.to_hdf("../examples/mydata.h5", "obj3", format="table")
pd.read_hdf("../examples/mydata.h5", "obj3", where=["index < 5"])

If you’d like, you can delete the HDF5 file you created, like so:

In [ ]:
import os
os.remove("../examples/mydata.h5")

<blockquote>
Note

If you are processing data that is stored on remote servers, like Amazon S3 or HDFS, using a different binary format designed for distributed storage like Apache Parquet may be more suitable.
</blockquote>

If you work with large quantities of data locally, I would encourage you to explore PyTables and h5py to see how they can suit your needs. Since many data analysis problems are I/O-bound (rather than CPU-bound), using a tool like HDF5 can massively accelerate your applications.

<blockquote>
Caution

HDF5 is not a database. It is best suited for write-once, read-many datasets. While data can be added to a file at any time, if multiple writers do so simultaneously, the file can become corrupted.
</blockquote>

# 6.3 Interacting with Web APIs

Many websites have public APIs providing data feeds via JSON or some other format. 

There are a number of ways to access these APIs from Python; one recommended method is the <b>requests</b> package, which can be installed with pip or conda:

In [ ]:
conda install requests

To find the last 30 GitHub issues for pandas on GitHub, we can make a <b>GET HTTP</b> request using the add-on requests library:

In [ ]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
resp

It’s a good practice to always call <b>raise_for_status</b> after using <b>requests.get</b> to check for HTTP errors.

The response object’s <b>json</b> method will return a Python object containing the parsed JSON data as a dictionary or list (depending on what JSON is returned):

In [ ]:
data = resp.json()
data[0]["title"]

Since the results retrieved are based on real-time data, what you see when you run this code will almost definitely be different.

Each element in <b>data</b> is a dictionary containing all of the data found on a GitHub issue page (except for the comments). 

We can pass data directly to <b>pandas.DataFrame</b> and extract fields of interest:

In [ ]:
issues = pd.DataFrame(data, columns=["number", "title",
                                     "labels", "state"])
issues

With a bit of elbow grease, you can create some higher-level interfaces to common web APIs that return <b>DataFrame</b> objects for more convenient analysis.

# 6.4 Interacting with Databases

In a business setting, a lot of data may not be stored in text or Excel files. 

SQL-based relational databases (such as SQL Server, PostgreSQL, and MySQL) are in wide use, and many alternative databases have become quite popular. 

The choice of database is usually dependent on the performance, data integrity, and scalability needs of an application.

pandas has some functions to simplify loading the results of a SQL query into a DataFrame. 

As an example, I’ll create a SQLite3 database using Python’s built-in sqlite3 driver:

In [ ]:
import sqlite3

query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""

con = sqlite3.connect("mydata.sqlite")
con.execute(query)
con.commit()

Then, insert a few rows of data:

In [ ]:
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(stmt, data)
con.commit()

Most Python SQL drivers return a list of tuples when selecting data from a table:

In [ ]:
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

You can pass the list of tuples to the DataFrame constructor, but you also need the column names, contained in the cursor’s description attribute. Note that for SQLite3, the cursor description only provides column names (the other fields, which are part of Python’s Database API specification, are None), but for some other database drivers, more column information is provided:

In [ ]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

This is quite a bit of munging that you’d rather not repeat each time you query the database. The SQLAlchemy project is a popular Python SQL toolkit that abstracts away many of the common differences between SQL databases. pandas has a read_sql function that enables you to read data easily from a general SQLAlchemy connection. You can install SQLAlchemy with conda like so:

In [ ]:
import sqlalchemy as sqla

Now, we’ll connect to the same SQLite database with SQLAlchemy and read data from the table created before:

In [ ]:
db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

In [ ]:
!rm mydata.sqlite

# 6.5 Conclusion

Getting access to data is frequently the first step in the data analysis process. We have looked at a number of useful tools in this chapter that should help you get started. In the upcoming chapters we will dig deeper into data wrangling, data visualization, time series analysis, and other topics.